Repository aerogear/mobile-security-service, pull requests merged in 2019-02, with the labels that each got.

#17 feat(apps-endpoint): added an endpoint to get all apps (AEROGEAR-8349)
  Gopkg.lock
  cmd/mobile-security-service/main.go
  pkg/models/app_versions.go
  pkg/models/apps.go
  pkg/web/apps/apps_http_handler.go
  pkg/web/apps/apps_http_handler_test.go
  pkg/web/apps/apps_psql_repository.go
  pkg/web/apps/apps_psql_repository_test.go
  pkg/web/apps/apps_service.go
  pkg/web/apps/apps_service_test.go
Labels: Verified, enhancement

#24 feature(git-hook): Added a pre-commit Git hook
  .githooks/pre-commit
  Makefile
  README.md
Labels: Verified

#25 feat: added brackets to if in githooks (AEROGEAR-8465)
  .githooks/commit-msg
Labels: Verification needed

#34 Adding generic errors and mapping to http errors
  pkg/httperrors/httperrors.go
  pkg/httperrors/httperrors_test.go
  pkg/models/errors.go
  pkg/web/apps/apps_http_handler.go
  pkg/web/apps/apps_service.go
Labels: Verified

#38 adding eslint
  ui/.eslintrc.json
  ui/package-lock.json
  ui/package.json
  ui/src/App.js
Labels: Verified

#41 Add redux to manage UI state
  ui/package-lock.json
  ui/package.json
  ui/src/configureStore.js
  ui/src/index.js
  ui/src/reducers/apps.js
Labels: Verified

#42 Updated /apps endpoint to get data from database (AEROGEAR-8526)
  Gopkg.lock
  Gopkg.toml
  api/swagger.yaml
  pkg/httperrors/httperrors.go
  pkg/httperrors/httperrors_test.go
  pkg/models/app.go
  pkg/models/errors.go
  pkg/test/api_test.go
  pkg/test/fixtures.go
  pkg/test/test.go
  pkg/web/apps/apps_psql_repository.go
  pkg/web/apps/apps_psql_repository_test.go
  pkg/web/apps/apps_repository.go
  pkg/web/apps/apps_service.go
  pkg/web/apps/apps_service_test.go
Labels: Verification needed

#69 fix(cover) : Coveralls should not consider the helpers data which are useful for the tests.
  pkg/helpers/db_seed.go
  pkg/helpers/fixtures.go
  pkg/web/apps/apps_psql_repository_test.go
  pkg/web/router/api_test.go
Labels: Verified

#30 feat(get-apps-by-id): Endpoint get apps by id (AEROGEAR-8350)
  Gopkg.lock
  pkg/helpers/fixtures.go
  pkg/helpers/isValidUUID.go
  pkg/models/app.go
  pkg/models/errors.go
  pkg/web/apps/app_service_mock_test.go
  pkg/web/apps/apps_http_handler.go
  pkg/web/apps/apps_http_handler_test.go
  pkg/web/apps/apps_psql_repository.go
  pkg/web/apps/apps_psql_repository_mock_test.go
  pkg/web/apps/apps_psql_repository_test.go
  pkg/web/apps/apps_repository.go
  pkg/web/apps/apps_repository_mock_test.go
  pkg/web/apps/apps_service.go
  pkg/web/apps/apps_service_mock_test.go
  pkg/web/apps/apps_service_test.go
  pkg/web/router/router.go
Labels: Verification needed
